const gameState = { points: Number(localStorage.getItem("eco-points") || 0), rewarded: JSON.parse(localStorage.getItem("eco-rewards") || "{}") };
const addReward = (key, value) => { if (gameState.rewarded[key]) return; gameState.rewarded[key] = true; gameState.points += value; localStorage.setItem("eco-points", gameState.points); localStorage.setItem("eco-rewards", JSON.stringify(gameState.rewarded)); updateProfile(); };
function updateProfile() {
  const levels = gameState.points >= 220 ? ["🌳", "Guardián del planeta", 100] : gameState.points >= 100 ? ["🌿", "Explorador ecológico", gameState.points - 100] : ["🌱", "Semilla verde", gameState.points];
  document.getElementById("total-points").textContent = gameState.points; document.getElementById("level-icon").textContent = levels[0]; document.getElementById("level-name").textContent = levels[1]; document.getElementById("level-message").textContent = gameState.points >= 220 ? "¡Dominaste todos los desafíos!" : `${gameState.points < 100 ? 100 - gameState.points : 220 - gameState.points} puntos para el siguiente nivel`; document.getElementById("level-progress").style.width = `${Math.min(100, levels[2])}%`;
}

document.querySelectorAll(".game-tab").forEach(tab => tab.addEventListener("click", () => { document.querySelectorAll(".game-tab").forEach(item => { item.classList.toggle("active", item === tab); item.setAttribute("aria-selected", String(item === tab)); }); document.querySelectorAll(".game-panel").forEach(panel => panel.hidden = panel.dataset.panel !== tab.dataset.game); }));

const sortItems = [
  ["🍌", "Cáscara de banano", "organico", "Puede convertirse en composta."], ["🥤", "Botella plástica limpia", "plastico", "Enjuágala, sécala y aplástala."], ["📦", "Caja de cartón limpia", "papel", "Dóblala para ahorrar espacio."], ["🍾", "Frasco de vidrio", "vidrio", "Retira la tapa y evita romperlo."], ["🔋", "Pila usada", "especial", "Llévala a un punto de recolección."], ["🍂", "Hojas secas", "organico", "Son excelentes para la composta."], ["📰", "Periódico seco", "papel", "Debe permanecer limpio y seco."], ["🧴", "Envase de champú", "plastico", "Vacía, enjuaga y seca el envase."], ["💡", "Bombilla dañada", "especial", "Necesita manejo especial; no va con vidrio."], ["🫙", "Tarro de vidrio", "vidrio", "Reutilízalo o entrégalo limpio."]
];
let sortOrder = [...sortItems].sort(() => Math.random() - .5), sortIndex = 0, sortScore = 0, sortAnswered = false;
function renderSort() { const item = sortOrder[sortIndex]; sortAnswered = false; document.getElementById("sort-icon").textContent = item[0]; document.getElementById("sort-name").textContent = item[1]; document.getElementById("sort-round").textContent = `Objeto ${sortIndex + 1} de ${sortOrder.length}`; document.getElementById("sort-progress").style.width = `${((sortIndex + 1) / sortOrder.length) * 100}%`; document.getElementById("sort-feedback").textContent = ""; document.getElementById("sort-next").hidden = true; document.querySelectorAll("#bin-options button").forEach(button => { button.disabled = false; button.classList.remove("correct", "wrong"); }); }
document.getElementById("bin-options").addEventListener("click", event => { const button = event.target.closest("button"); if (!button || sortAnswered) return; sortAnswered = true; const item = sortOrder[sortIndex], correct = button.dataset.bin === item[2]; if (correct) sortScore += 10; document.getElementById("sort-score").textContent = sortScore; document.querySelectorAll("#bin-options button").forEach(option => { option.disabled = true; if (option.dataset.bin === item[2]) option.classList.add("correct"); }); if (!correct) button.classList.add("wrong"); document.getElementById("sort-feedback").textContent = `${correct ? "¡Muy bien!" : "Casi."} ${item[3]}`; document.getElementById("sort-next").hidden = false; });
document.getElementById("sort-next").addEventListener("click", () => { if (sortIndex < sortOrder.length - 1) { sortIndex++; renderSort(); return; } addReward("sort", sortScore); document.querySelector("#sort-game .play-card").innerHTML = `<div class="game-complete"><span>🏆</span><h3>¡Clasificación completada!</h3><p>Lograste <b>${sortScore} de 100 puntos</b>. Tus EcoPuntos ya están guardados.</p><button class="button button-primary" onclick="location.reload()">Jugar otra vez ↻</button></div>`; });

const memoryPairs = [["🍌", "Orgánico"], ["🧴", "Plástico"], ["📦", "Papel"], ["🫙", "Vidrio"], ["🔋", "Especial"], ["🥫", "Metal"]]; let memoryFirst = null, memoryLock = false, memoryMoves = 0, memoryMatches = 0;
function buildMemory() { const cards = memoryPairs.flatMap((pair, id) => [{ id, text: pair[0] }, { id, text: pair[1] }]).sort(() => Math.random() - .5); const board = document.getElementById("memory-board"); board.innerHTML = cards.map((card, index) => `<button class="memory-card" data-pair="${card.id}" data-index="${index}" aria-label="Tarjeta oculta"><span class="card-back">?</span><span class="card-front">${card.text}</span></button>`).join(""); memoryFirst = null; memoryLock = false; memoryMoves = 0; memoryMatches = 0; document.getElementById("memory-moves").textContent = "0"; document.getElementById("memory-message").textContent = "Selecciona dos tarjetas para comenzar."; }
document.getElementById("memory-board").addEventListener("click", event => { const card = event.target.closest(".memory-card"); if (!card || memoryLock || card.classList.contains("matched") || card === memoryFirst) return; card.classList.add("flipped"); if (!memoryFirst) { memoryFirst = card; return; } memoryMoves++; document.getElementById("memory-moves").textContent = memoryMoves; if (card.dataset.pair === memoryFirst.dataset.pair) { card.classList.add("matched"); memoryFirst.classList.add("matched"); memoryFirst = null; memoryMatches++; document.getElementById("memory-message").textContent = "¡Pareja encontrada!"; if (memoryMatches === memoryPairs.length) { const reward = Math.max(20, 90 - Math.max(0, memoryMoves - 6) * 5); addReward("memory", reward); document.getElementById("memory-message").innerHTML = `¡Tablero completo en <b>${memoryMoves} movimientos</b>! Ganaste ${reward} EcoPuntos.`; } return; } memoryLock = true; document.getElementById("memory-message").textContent = "No coinciden. Observa y recuerda."; const previous = memoryFirst; memoryFirst = null; setTimeout(() => { card.classList.remove("flipped"); previous.classList.remove("flipped"); memoryLock = false; }, 750); });
document.getElementById("memory-restart").addEventListener("click", buildMemory);

const truths = [["Las botellas y envases deben estar vacíos, limpios y secos antes de reciclarse.", true, "Los restos de comida contaminan otros materiales."], ["Una caja de pizza con mucha grasa puede ir completa al contenedor de papel.", false, "La parte grasosa no se recicla; separa únicamente el cartón limpio."], ["Reutilizar un frasco es preferible a desecharlo de inmediato.", true, "Reutilizar alarga la vida del objeto y evita residuos."], ["Las pilas usadas pueden mezclarse con la basura común.", false, "Las pilas necesitan un punto de recolección especial."], ["Aplastar las botellas plásticas secas ayuda a ahorrar espacio.", true, "Compactarlas facilita su almacenamiento y transporte."], ["Todo objeto de vidrio se recicla junto con las botellas.", false, "Espejos, bombillas y cerámica tienen composiciones diferentes."], ["Reducir el consumo debe ocurrir antes que reciclar.", true, "La mejor opción es evitar generar el residuo."], ["Una servilleta usada pertenece al contenedor de papel limpio.", false, "La humedad y los restos orgánicos impiden reciclarla como papel."]]; let truthIndex = 0, truthScore = 0, truthAnswered = false;
function renderTruth() { const item = truths[truthIndex]; truthAnswered = false; document.getElementById("truth-statement").textContent = item[0]; document.getElementById("truth-round").textContent = `Afirmación ${truthIndex + 1} de ${truths.length}`; document.getElementById("truth-progress").style.width = `${((truthIndex + 1) / truths.length) * 100}%`; document.getElementById("truth-feedback").textContent = ""; document.getElementById("truth-next").hidden = true; document.querySelectorAll(".truth-options button").forEach(button => { button.disabled = false; button.classList.remove("correct", "wrong"); }); }
document.querySelector(".truth-options").addEventListener("click", event => { const button = event.target.closest("button"); if (!button || truthAnswered) return; truthAnswered = true; const item = truths[truthIndex], value = button.dataset.value === "true", correct = value === item[1]; if (correct) truthScore++; document.getElementById("truth-score").textContent = truthScore; document.querySelectorAll(".truth-options button").forEach(option => { option.disabled = true; if ((option.dataset.value === "true") === item[1]) option.classList.add("correct"); }); if (!correct) button.classList.add("wrong"); document.getElementById("truth-feedback").textContent = `${correct ? "¡Correcto!" : "No exactamente."} ${item[2]}`; document.getElementById("truth-next").hidden = false; });
document.getElementById("truth-next").addEventListener("click", () => { if (truthIndex < truths.length - 1) { truthIndex++; renderTruth(); return; } const reward = truthScore * 10; addReward("truth", reward); document.querySelector(".truth-card").innerHTML = `<div class="game-complete"><span>🌍</span><h3>¡Reto completado!</h3><p>Acertaste <b>${truthScore} de ${truths.length}</b> y ganaste ${reward} EcoPuntos.</p><button class="button button-primary" onclick="location.reload()">Jugar otra vez ↻</button></div>`; });

updateProfile(); renderSort(); buildMemory(); renderTruth();
